# copyright: 2024 EUMETSAT
# license: LICENSE.txt
name: cmts_learn_olci
channels:
  - conda-forge
  - cmts
  - eumetsat
dependencies:
  # Core
  - conda-forge::bokeh=3.2.1
  - conda-forge::cartopy
  - conda-forge::cmocean
  - conda-forge::dask
  - conda-forge::distributed
  - conda-forge::hda
  - conda-forge::ipywidgets
  - conda-forge::jupyterlab
  - conda-forge::matplotlib
  - conda-forge::netcdf4
  - conda-forge::python=3.10
  - conda-forge::scipy
  - conda-forge::xarray
  # External
  - cmts::eumartools
  - eumetsat::eumdac
  # Extension
  - conda-forge::scikit-image
  - conda-forge::shapely
  # Extension: ThoMaS support
  - conda-forge::beautifulsoup4
  - conda-forge::cdsapi
  - conda-forge::ephem
  - conda-forge::pandas
  - conda-forge::urllib3